### ISSUE TITLE
今日のGitHubチーム実践の内容まとめは誰かする？

### ISSUE THREAD

**Issue by m4kvn** [miraikeitai2017/Android-Study#5]
今日のGitHubチーム利用実践の内容は、どこかにリソースとして残しておきたいと思っています。
それでその内容を僕がまとめてもいいと思ったのですが、復習も含め誰かやりたい人はいますか？

### issues の使い方リソース

- [チーム開発を変える「GitHub」とは？〜Issuesの使い方〜](https://seleck.cc/647)

**Comment by m4kvn** [comment]
僕がつくちゃってよければ **Add your reaction** ここから 👍 してください。
逆にやりたい人は 🥇 してください。

あと他の提案としては、今日やった流れだけを僕が書き出して、
内容を他の人が復習を踏まえてやるのもありだと思います。

![](https://www.evernote.com/l/As13GBnZ6fpNoo9EnxG6sNI6KN-1kFkJqAoB/image.png)

**Comment by MasahiroSaito** [comment]
## やったこと

- GitHubのチーム作成
- miraikeitai2017にAndroid-Studyを作成

**Comment by m4kvn** [comment]
# やったこと

1. 勉強会日程調整
1. 勉強進捗報告
1. 実機テスト
1. [チームでのGitHub利用実践](#team)
1. [issuesの使い方](#issue)

## <a name="team">チームでのGitHub利用実践</a>

1.  miraikeitai2017にAndroidチームを作成
1. miraikeitai2017にAndroid-Studyを作成
1. Android-StudyをGitKrakenでクローン
1. GitKrakenでブランチ `name/study` を作成
1. 適当なMarkdownファイルを作成
1. GitKrakenでローカルリポジトリにコミット
1. GitKrakenでリモートにブランチとコミットをプッシュ
1. GitKrakenからmasterブランチへのプルリクエストを作成
1. GitHubでプルリクエスト一覧を確認
1. GitHubで他の人からのプルリクエストを承認
1. みんなのブランチがmasterへマージされた
1. GitKrakenでmasterブランチをチェックアウト
1. GitKrakenでmasterブランチをリモートからローカルへプル
1. GitKrakenでローカルのmasterブランチを `name/study` ブランチへマージ

## <a name="issue">issuesの使い方</a>

1. リポジトリのissuesページへ移動
1. `New issue` からissueを作成
1. Markdown形式で書き込む
1. `Close` でissueを閉じる
